### ISSUE TITLE
HBLoader

### ISSUE THREAD

**Issue by Leerz** [hartmannaf/arm9loaderhax#1]
Loved the bootctr 3dsx,a9lh took hb way, can this be done? 
I know i can press R on aurei to load it via menuhax, but it will be great to skip the debug and have higher boot rate with a9lh for hb -- i know i can also boot it with hb.cia 
:)

**Comment by Hartie95** [comment]
Its not possible to boot 3dsx files on arm9. They need the full kernel and services started, because they access them to do everything. So the only ways are to use cia versions of homebrew, or start the homebrew launcher after the system is loaded.
