### ISSUE TITLE
Version 0.4 Alpha does not work with Decrypt9

### ISSUE THREAD

**Issue by astronautlevel2** [hartmannaf/arm9loaderhax#3]
Attempting to use version 0.4 Alpha will not boot decrypt 9 (boots default entry instead). Decrypt9 works on version 0.3.

**Comment by Hartie95** [comment]
Could you please give me a link to the payload, and give me your configuration?

**Comment by pbanj** [comment]
i just installed 0.4.1 and decrypt9 is working just fine. i was using 0.4 before and didnt have an issue with decrypt9 either. it could be they have an offset set for the bin file. when using the bin file the offset needs to be 0

**Comment by Hartie95** [comment]
That's why I want to see the configuration. Also it should not be a button press timing issue, since I tested different scenarios when to press it(like holding it on boot, or while waiting for the key).

**Comment by astronautlevel2** [comment]
This was specific to version 0.4 Alpha. I can confirm that it works in version 0.4.1 alpha (meant to close this earlier).

**Comment by Hartie95** [comment]
Then it apeared, because you haven't set a key delay, and I had the wrong default values, so it used 0 instead of 100
