### ISSUE TITLE
[Suggestion] Get rid of white flash during boot

### ISSUE THREAD

**Issue by ghost** [hartmannaf/arm9loaderhax#5]
Is there any way to remove the white flash at the beginning? I love this app but it would be AWESOME if you could find out how to get rid of it.

**Comment by Hartie95** [comment]
You could disable screen init if not needed. Otherwise I dont know what you mean with white flash. Also which version are you using.

**Comment by ghost** [comment]
I'm using Aurora Wrights Screen init payload BUT - I edited the screen brightness so it wouldn't show the screen init but I could still use Arm9LoaderHay (it's exactly like Arm9Select). I'm using select to boot into BootCtr9 so that it will boot into the AuReiNand settings. Here's a video of whats happening: https://www.dropbox.com/s/0yhot00oec70jrd/BootCTR9%20Problem.MOV?dl=0

and here's my boot config: https://www.dropbox.com/s/3f3eiv66zhdr4l1/boot_config.ini?dl=0

So is there a way to edit either my A9LH or BootCtr9 to support my setup?

**Comment by ghost** [comment]
PS: I don't care about boot images at all if I'd have to edit that feature out to make it work

**Comment by ghost** [comment]
I'm using the newest public release

**Comment by Hartie95** [comment]
Could check out the newest devbuild from the arm9laoderhax thread on gbatemp?

**Comment by ghost** [comment]
Can you give me a link please? I'm not sure where you mean to go :P

**Comment by Hartie95** [comment]
Oh yes, I wanted to add the link later(wrote it on my mobile phone).
Here is the link:
https://gbatemp.net/threads/arm9loader-technical-details-and-discussion.408537/page-197#post-6255753

**Comment by ghost** [comment]
Fixed! Could you put this as an official release in your Github?

**Comment by Hartie95** [comment]
The changes are not final atm, I'm restructuring the code atm, after it's finished I will make the next release.

**Comment by ghost** [comment]
Sounds good! Great work btw! is there any chance to only be able to install bootctr9 with only the arm9loaderhax bin without your fork or is there something that I'm forgetting? (I know these are very different) but why does CtrBootManager9 only have one bin file while this has to have 2?

**Comment by Hartie95** [comment]
ctrbootmanager9 is using a small loader.bin, which is  loaded at an other address. This is included inside of its arm9loaderhax.bin. If you are using the arm9loaderhax.bin to load the arm9bootloader.bin, it uses a similar system, but with those two files separated, but maybe in future I will change it. 
But its possible to load the arm9bootloader.bin and the configuration from some folders(like a9lh, arm9loaderhax and some others).
Using the arm9loaderhax stage2 payload from this fork this is also possible.

**Comment by ghost** [comment]
Awesome! Personally hoping for this future feature! Thanks for helping me by the way! Great job!
