### ISSUE TITLE
Release latest? Add combo and password support?

### ISSUE THREAD

**Issue by ghost** [hartmannaf/arm9loaderhax#7]
When will you release the latest BootCtr9?

Can you add combo button support and password support that arm9loaderhay has here: https://gbatemp.net/threads/arm9loaderhay-my-own-take-on-a-a9lh-file-select.420325/ ? That would make this payload 100 percent cooler!

**Comment by Hartie95** [comment]
I have much to do atm, so I'm not able to test my changes enough to release a new full version.
I'm also working on an ARM11 API for ARM9 Homebrew, to allow them to change the display state and more, without the need to include a full ARM11 screen init payload.

Combo and password support is not planned atm, but maybe I will set them as a targets for releases after version 1.0(which is my current goal).

If you want more recent releases check out the arm9loaderhax technical disscusion thread at gbatemp for dev builds. They are normaly working without a problem, but they could still have bugs.

**Comment by ghost** [comment]
Good news! Arm9LoaderHay is now open source! Thank you for all of the work you've done so far!! https://gbatemp.net/attachments/arm9loaderhay-zip.47921/

**Comment by Hartie95** [comment]
I still have an idea, on how to implement password support, and I will do it in the next time (after I implemented A9LH Netloader Companion support.

**Comment by Hartie95** [comment]
While combo support is still not planned atm, I added passwort support.
After some code cleanups I will push the code and update the wiki for it.
I will also release the Pre 1.0 in the next time I think.

**Comment by Hartie95** [comment]
So the code is now pushed, and the current state will be released as a RC version for the pre 1.0 release.

**Comment by ghost** [comment]
Omg awesome!!! I love the new passwerd support! love iiiit! Thank you so much! Keep me up with any details please!

**Comment by Hartie95** [comment]
Pre 1.0 is now released, together with an official [release thread](http://gbatemp.net/threads/release-the-bootctr9-release-thread.435347/). on gbatemp.
Its nearly the same as the RC2 version, but with the version changed.

I will close it for now and I will reopen it, if I add combination support.

**Comment by ghost** [comment]
Ok sounds awesome!! :)
